base:
  project: bank_customer_churn
  data_dir: data
  data_fname: Churn_Modelling.csv
  cat_cols:
  - Geography
  num_cols:
  - CreditScore
  - Age
  - Tenure
  - Balance
  - NumOfProducts
  - HasCrCard
  - IsActiveMember
  - EstimatedSalary
  targ_col: Exited
  random_state: 10
  model_dir: model/

data_split:
  test_size: 0.28

train:
  model_type: randomforest
  params:
    n_estimators: 500
    max_depth: 5

eval:
  perm_imp_model_path: models/perm_imp.joblib
